### ISSUE TITLE
Question about repo that contains a theme

### ISSUE THREAD

**Issue by BenBroide** [bowiedev/github-action-wpengine-ssh-deploy#1]
What if the repo we we want to deploy contains only a WordPress, not the full site.
What do I need to adjust to push the only the theme to the correct folder?

**Comment by bowiedev** [comment]
Currently this is built to deploy to a WP project root. 
You could initiate a repo from the root of your WP project and create a .gitignore file that includes everything but the theme directory youre working on. 

I'll be looking into an update to include a destination path.

**Comment by bowiedev** [comment]
Hey Ben! This is now possible with the TPO_DIR 👍 
See README for more details and let me know if you have any other questions.
