### ISSUE TITLE
Source Folder Parameter

### ISSUE THREAD

**Issue by csmoakpax8** [bowiedev/github-action-wpengine-ssh-deploy#4]
Would you be willing to add a param to accept a source folder. I have my wordpress theme in a folder.

I cloned your repo and added the param. It was only a matter of "cd'ing" prior to calling `rsync ...`. It might be possible with rsync, im just not good at shell.
 
https://github.com/pax8/github-action-wpengine-ssh-deploy

**Comment by bowiedev** [comment]
Hey there! 
yes thats a stellar idea for anyone who wants to have a source/destination specification. It's been included directly as a param that drops right into the rsync one liner. Works in my tests but feel free to test it out. The sample yaml has been updated to reflect the new params.
